name: Container
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    # 二重実行を防ぐ
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15
    if: ${{ github.repository == 'teruyamato0731/pio-template' }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/pio-template-devcontainer
          cacheFrom: ghcr.io/${{ github.repository_owner }}/pio-template-devcontainer
          skipContainerUserIdUpdate: true
