name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    # 二重実行を防ぐ
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/teruyamato0731/pio-template-devcontainer
          push: never
          runCmd: pio run
