name: Template Cleanup
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  template-cleanup:
    runs-on: ubuntu-22.04
    # 二重実行を防ぐ
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.repository != 'teruyamato0731/pio-template' }}
    steps:
      - uses: actions/checkout@v3

      - name: Cleanup
        shell: bash
        run: |
          set -euxo pipefail
          rm .github/workflows/*.tmp.yml
          sed -i -e "s/pio-template/${REPO_NAME}/g" .devcontainer/devcontainer.json .devcontainer/docker-compose.yml README.md
          sed -i -e "s/teruyamato0731/${GITHUB_REPOSITORY_OWNER}/g" README.md
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Template cleanup"
          git push origin main
